services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: # Add to network
      - app_net

  redis:
    image: redis:6-alpine
    networks: # Add to network
      - app_net

  backend:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8001:8000"
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks: # This was missing
      - app_net

  frontend:
    build: ./frontend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./frontend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - backend
    networks: # Add to network
      - app_net

# Define the shared network
networks:
  app_net:
    driver: bridge

volumes:
  postgres_data: